name: websocket_app
description: Arduino Connect App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  dart_net_work:
    path: ./submodules/dart_net_work
  screen_view:
    path: ./submodules/screen_view
  i18n_app:
    path: ./submodules/i18n_app
  app_domain:
    path: ./submodules/app_domain
  app_database:
    path: ./submodules/app_database
  app_websocket:
    path: ./submodules/app_websocket

  hive_flutter: ^1.1.0
  hive: ^2.0.5
  logger: any
  flutter_bloc: ^8.0.1
  injectable: ^1.5.3
  get_it: ^7.2.0
  rxdart: ^0.27.3
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner:
  json_serializable: ^6.1.3
  retrofit_generator: ^4.2.0
  injectable_generator:

flutter:
  uses-material-design: true

  assets:
    - submodules/screen_view/assets/svg/background/
    - submodules/screen_view/assets/svg/alert/