name: app_websocket
description: Websocket app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dart_net_work:
    path: ../dart_net_work

  logger: any
  web_socket_channel: ^2.1.0
  injectable: ^1.5.3
  get_it: ^7.2.0
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner:
  json_serializable: ^6.1.3
  injectable_generator: