version: "3.7"

services:
  websocket-api:
    container_name: websocket-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "172.17.0.1:8080:8080"
      - "127.0.0.1:8080:8080"

